---

apiVersion: v1
kind: Namespace
metadata:
  name: qotm

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
  namespace: qotm
spec:
  replicas: 1
  selector:
    matchLabels:
    app: quote
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: quote
    spec:
      terminationGracePeriodSeconds: 5
      initContainers:
      - name: qotm-init
        image: busybox:1.34.1
        command: ['sh', '-c', 'dd if=/dev/zero of=/dev/shm/cache bs=1M count=64']
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"
          limits:
            memory: "64Mi"
            cpu: "500m"        
      containers:
      - name: qotm-frontend
        image: docker.io/datawire/qotm:1.6
        command: ['sh', '-c', 'echo Reticulating splines... ; sleep 10 ; python3 qotm/qotm.py']
        ports:
        - name: http
          containerPort: 5000
        livenessProbe:
          failureThreshold: 1
          periodSeconds: 5
          httpGet:
            path: /health
            port: 5000
        readinessProbe:
          failureThreshold: 1
          periodSeconds: 5
          httpGet:
            path: /health
            port: 5000  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: quote-svc
  namespace: qotm
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: quote
